#!/bin/bash
clear

echo -e " \e[94m"
title="====================================== "
printf "%*s\n" 60 "$title"
title="   . .       . .     . . .     . .     "
printf "%*s\n" 60 "$title"
title=" .     .    .          .     .     .   "
printf "%*s\n" 60 "$title"
title=" .     .    .          .     .     .   "
printf "%*s\n" 60 "$title"
title=" .     .    .          .     .     .   "
printf "%*s\n" 60 "$title"
title="   . .       . .       .       . .     "
printf "%*s\n" 60 "$title"
title="                                       "
printf "%*s\n" 60 "$title"
title="             ............              "
printf "%*s\n" 60 "$title"
title="             ............              "
printf "%*s\n" 60 "$title"
title="                                       "
printf "%*s\n" 60 "$title"
title="        . .     . . .     .   .        "
printf "%*s\n" 60 "$title"
title="        .  .    .          . .         "
printf "%*s\n" 60 "$title"
title="        .  .    . . .       .          "
printf "%*s\n" 60 "$title"
title="        .  .    .          . .         "
printf "%*s\n" 60 "$title"
title="        . .     . . .     .   .        "
printf "%*s\n" 60 "$title"
title=" ===================================== "
printf "%*s\n" 60 "$title"

echo -e " \e[94m"
PS3='Please enter your choice: '
options=("Compile Kernel" "Clean Old Files" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Compile Kernel")
echo -e "\e[35mThis Script Edited By Nyks45\e[0m"
echo -e "\e[35mSay Thanks To Him İf He Helped U\e[0m"
echo -e "\e[92mApplying Build Settings\e[0m"

export ARCH=x86_64
export CCOMPILE=$CROSS_COMPILE
export CROSS_COMPILE=x86_64-linux-

#CONFIGS
export SLEEP=1
echo -e "\e[93mSetting CPU Cores/Threads\e[0m"
export CPUS=`nproc`
echo -e "\e[93mSetting Toolchain Location/Threads\e[0m"
echo -e "\e[32mSetting Version Number\e[0m"
echo -e " \e[35m"
read -p "Enter Version Number : " s
v='v'
export VER=$v$s
echo -e "\e[31mVersion Number Is Setting To $v$sS\e[0m"

echo -e "\e[95mSetting Defconfig\e[0m"
export DEFCONFIG=OctoDex_Kernel_defconfig
echo -e "\e[96mSetting bzImage Location For OctoDex kernel By Nyks45 Of XDA\e[0m"
export BZIMAGE=arch/x86/boot/bzImage
echo -e "\e[90mEnviroment Setup Complete Now Moving To Compiling\e[0m"

#Build
sleep 1
sleep $SLEEP
echo -e "\e[31mStarting Build Process\e[0m"
export USE_CCACHE=1
sleep $SLEEP
if [ -f .config ];
then
   echo -e "\e[95m.config exists\e[0m"
   echo -e "\e[95mContinuing To Compiler\e[0m"
   sleep $SLEEP
else
   echo -e "\e[95m.config Does Not Exists\e[0m"
   echo -e "\e[95mCompiling From $DEFCONFIG\e[0m"
echo -e " \e[94m"
   make $DEFCONFIG
   sleep $SLEEP
fi
echo -e "\e[34mCompiling OctoDex Kernel\e[0m"
make $EV -j$CPUS

if [ -f $BZIMAGE ];
then
   echo -e "\e[95m$BZIMAGE exists\e[0m"
   echo -e "\e[95mCompile Complete Continuing To Packing\e[0m"
   sleep $SLEEP
else
   echo -e "\e[95m$BZIMAGE Does Not Exists Please Check For Compile Errors\e[0m"
   echo -e "\e[95mNow exiting script\e[0m"
   sleep $SLEEP
   exit 0
fi
clear
echo -e " \e[94m"
echo -e "\e[31mScript Made By Nyks45 From XDA\e[0m"
echo -e " \e[94m"
printf "Say Him To Thanks If He Helped You \n\n"
echo -e " \e[94m"
echo "Version Number = $VER"
echo -e " \e[94m"
echo "Build complete"

#Kernel Packing
echo -e "\e[95mOctoDex Kernel Packing\e[0m"
echo -e "\e[95mStarting Packing To Recovery Flashable Zip\e[0m"
cd out/
echo "bzimage"
rm -rf bzImage *.zip
sleep $SLEEP
echo "Copying bzImage"
mv ../arch/x86/boot/bzImage bzImage
sleep $SLEEP
echo -e "\e[95mCompiling OctoDex_"$VER".zip\e[0m"
find . -type f -exec zip OctoDex_"$VER".zip {} +
nowf=$(date +"%T")
cd ..
printf "\n\n zip created\n"
rm out/bzImage
printf "\n\nzip created\n"
echo -e " \e[94m"
title="====================================== "
printf "%*s\n" 60 "$title"
title="   . .       . .     . . .     . .     "
printf "%*s\n" 60 "$title"
title=" .     .    .          .     .     .   "
printf "%*s\n" 60 "$title"
title=" .     .    .          .     .     .   "
printf "%*s\n" 60 "$title"
title=" .     .    .          .     .     .   "
printf "%*s\n" 60 "$title"
title="   . .       . .       .       . .     "
printf "%*s\n" 60 "$title"
title="                                       "
printf "%*s\n" 60 "$title"
title="             ............              "
printf "%*s\n" 60 "$title"
title="             ............              "
printf "%*s\n" 60 "$title"
title="                                       "
printf "%*s\n" 60 "$title"
title="        . .     . . .     .   .        "
printf "%*s\n" 60 "$title"
title="        .  .    .          . .         "
printf "%*s\n" 60 "$title"
title="        .  .    . . .       .          "
printf "%*s\n" 60 "$title"
title="        .  .    .          . .         "
printf "%*s\n" 60 "$title"
title="        . .     . . .     .   .        "
printf "%*s\n" 60 "$title"
title=" ===================================== "
printf "%*s\n" 60 "$title"

            ;;
        "Clean Old Files")
read -r -p "Are you sure? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
        make clean&make mrproper
        break
        ;;
    *)
        break
        ;;
esac
echo "Cleaning Out Compiled Files"
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done